### ISSUE TITLE
Varjohirviö ei aiheuta chasemusiikkia tai muita efektejä saapumisellaan

### ISSUE THREAD

**Issue by Honk1n** [JaniRantanen/troubled_girl#10]
**Kuvaa virhe**
Varjohirviö ei aiheuta chasemusiikkia tai muita efektejä saapumisellaan

Toivottu toiminta:
Chase musiikki alkaisi soimaan. 
 - Käyttöjärjestelmä
 - Selain (IE, Edge, Google Chrome, Mozilla Firefox)
 - Selainversio

**Comment by JaniRantanen** [comment]
Ristiriidassa muiden speksien kanssa. Aiheuttaa varmasti päällekkäisyyksiä musiikeissa -> Ei mahdollista korjata tällä aikataululla. Suljetaan toistaiseksi.
