### ISSUE TITLE
Ilmassa tehtävän Dashin animaatio ei näy jos sen aikana painetaan suuntanäppäintä

### ISSUE THREAD

**Issue by Honk1n** [JaniRantanen/troubled_girl#8]
**Kuvaa virhe**
Ilmassa tehtävä dash (kaksi kertaa sivulle ilmassa) animaatio ei näy jos pelaaja painaa suuntanäppäintä

**Miten todentaa / milloin virhe ilmenee**
Onko jotkin tietyt askeleet, jolla virhe toistuu yhä uudelleen? Alla esimerkki

1. varmista että dash on unlockattu (tarvittaessa kirjoita: girl peliruudulla laittaaksesi koodit päälle)
2. hyppää ja paina oikealle tai vasemmalle kahdesti
3. paina suuntapainiketta pohjassa
4. animaatiossa on hyppyanimaation jokin frame, joka ei animoi

**Odotettu toiminta**
Kun dash tehdään animaatio keskeytyy vain jos hypätään uudestaan tai osutaan maahan.

**Kuvakaappaukset**

**Tekniset tiedot**
- Sovelluksen versio (näkyy aloitusruudussa)
 - Käyttöjärjestelmä
 - Selain (IE, Edge, Google Chrome, Mozilla Firefox)
 - Selainversio

**Comment by JaniRantanen** [comment]
Pelihahmon animaatiostateissa tosiaan oli dash-animaation yliajaminen toisella animaatiolla. Dash sieltä yritti puskea läpi, mutta jokaisen updateloopin sisällä se resetoitui johonkin toiseen (falling, idle, running esim). Dash pitäisi nyt toimia kuten kuvattu.

Korjattu development buildiin, yhdistetään masteriin seuraavassa versiossa.
